### PR TITLE
Adapt for projects move to GitHub

### PR DESCRIPTION
**Pull request by thresheek**

### CODE REVIEW

**Comment by oxpa** [comment]
Should we add gitignore similar to .hgignore we have at the moment?
Also, maybe, include all the files created by makefiles to track targets, while at it.

**Comment by thresheek** [comment]
Good idea with to .hgignore/.gitignore, indeed we should have it.

I'm not sure tracking targets belong to this PR, but we can have a separate one for it.  Can you elaborate on it opening a new issue?

**Comment by oxpa** [comment]
A pull request is the best issue =) Will submit one for `.gitignore` improvements

**Comment by thresheek** [comment]
I think you can add commits to this PR for `.gitignore` stuff directly, too.

**Review by oxpa — APPROVED** [review]

**Comment by thresheek** [comment]
Well, I would think we should remove .hgignore with this change too?

**Comment by oxpa** [comment]
Yep, makes sense. Updated the PR

**Comment by thresheek** [comment]
Added contribs/tarballs .gitignore (we need this directory on checkout)

**Comment by oxpa** [comment]
I was wrong in regards to "tarballs" entry: we should probably have a file inside that directory to keep it. I can't find a way to include it otherwise.
But the last change will "include" directories created during a normal build inside `contrib/` (like `nginx` and `xslcript`). We can, probably, fix this though on it's own...

**Pull request merged**
